package ch.uzh.ifi.seal.soprafs19.constant;

public enum GameStatus {
    CHOSING_GAME_MODE, CHOSING_GODCARDS, PICKING_GODCARDS,
    SettingFigurinesp1f1, SettingFigurinesp1f2, SettingFigurinesp2f1, SettingFigurinesp2f2,
    MOVING_STARTINGPLAYER, BUILDING_STARTINGPLAYER, MOVING_NONSTARTINGPLAYER, BUILDING_NONSTARTINGPLAYER,
    STARTINGPLAYER_WON, NONSTARTINGPLAYER_WON
}
